### ISSUE TITLE
FileNotFoundError /run/systemd/system/var-lib-systemd\\x2dswap-swapfc-1.swap

### ISSUE THREAD

**Issue by MartinX3** [Nefelim4ag/systemd-swap#198]
In m journalctl every day I see:

```
Jan 16 23:47:12 deus-ex-machina systemd-swap[748]: INFO: swapFC: free ram: 34 < 35 - allocate chunk:  1
Jan 16 23:47:13 deus-ex-machina systemd[1]: Activating swap Swap File...
Jan 16 23:47:13 deus-ex-machina kernel: Adding 262140k swap on /var/lib/systemd-swap/swapfc/1.  Priority:50 extents:21 across:9732092k SSDscFS
Jan 16 23:47:13 deus-ex-machina systemd[1]: Activated swap Swap File.
Jan 16 23:49:59 deus-ex-machina systemd[1]: Stopping Manage swap spaces on zram, files and partitions....
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]: INFO: swapFC: swapoff /var/lib/systemd-swap/swapfc/1
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]: INFO: Removed /run/systemd/system/var-lib-systemd\x2dswap-swapfc-1.swap
Jan 16 23:49:59 deus-ex-machina systemd[1419]: var-lib-systemd\x2dswap-swapfc-1.swap: Succeeded.
Jan 16 23:49:59 deus-ex-machina systemd[1]: var-lib-systemd\x2dswap-swapfc-1.swap: Succeeded.
Jan 16 23:49:59 deus-ex-machina systemd[1]: Deactivated swap Swap File.
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]: INFO: Removed /var/lib/systemd-swap/swapfc/1
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]: Traceback (most recent call last):
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:   File "/usr/bin/systemd-swap", line 904, in <module>
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:     main()
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:   File "/usr/bin/systemd-swap", line 894, in main
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:     stop()
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:   File "/usr/bin/systemd-swap", line 765, in stop
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:     for unit_path in filter(lambda u: "zram" in read(u), swap_units):
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:   File "/usr/bin/systemd-swap", line 765, in <lambda>
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:     for unit_path in filter(lambda u: "zram" in read(u), swap_units):
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:   File "/usr/bin/systemd-swap", line 454, in read
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]:     with open(file) as f:
Jan 16 23:49:59 deus-ex-machina systemd-swap[65436]: FileNotFoundError: [Errno 2] No such file or directory: '/run/systemd/system/var-lib-systemd\\x2dswap-swapfc-1.swap'
Jan 16 23:49:59 deus-ex-machina systemd[1]: systemd-swap.service: Control process exited, code=exited, status=1/FAILURE
Jan 16 23:49:59 deus-ex-machina systemd[1]: systemd-swap.service: Failed with result 'exit-code'.
Jan 16 23:49:59 deus-ex-machina systemd[1]: Stopped Manage swap spaces on zram, files and partitions..
Jan 16 23:49:59 deus-ex-machina audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-swap comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivating swap /dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_S3Z9NB0KB38256K-part3...
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:17.0\x2data\x2d1.0\x2dpart3.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-path/pci-0000:00:17.0-ata-1.0-part3.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2duuid-4a747812\x2dcab0\x2d438b\x2dace1\x2da46b73f00d4a.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-uuid/4a747812-cab0-438b-ace1-a46b73f00d4a.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2did-wwn\x2d0x5002538e409f2d79\x2dpart3.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-id/wwn-0x5002538e409f2d79-part3.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2did-ata\x2dSamsung_SSD_860_EVO_1TB_S3Z9NB0KB38256K\x2dpart3.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_S3Z9NB0KB38256K-part3.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2dpartuuid-cb1d55ae\x2db95f\x2d4406\x2d802d\x2dd6a26616709a.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-partuuid/cb1d55ae-b95f-4406-802d-d6a26616709a.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:17.0\x2data\x2d1\x2dpart3.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap /dev/disk/by-path/pci-0000:00:17.0-ata-1-part3.
Jan 16 23:51:30 deus-ex-machina systemd[1]: dev-sda3.swap: Succeeded.
Jan 16 23:51:30 deus-ex-machina systemd[1]: Deactivated swap Swap Partition.
```

**Comment by oold** [comment]
The affected code has changed since the bug was reported. Please reopen the issue if it's reproducible with the latest version or open another issue.
